---
# handlers file for Web
- name: Start httpd
  service:
    name: httpd
    state: started

- name: Stop httpd
  service:
    name: httpd
    state: stopped

- name: reload httpd
  service:
    name: httpd
    state: reloaded
