---
# tasks file for Web
- name: install EPEL release
  yum:
   name: epel-release
   state: latest

- name: Update(s) server(s) web
  yum:
   name: '*'
   state: latest

- name: install httpd and other
  yum: name={{ item }} state=latest
  with_items:
   - httpd
   - php
   - php-mysql
  notify:
    - Start httpd
