---
# handlers file for apache
- name: start apache
  service:
    name: apache
    state: started

- name: stop apache
  service:
    name: apache
    state: stopped

- name: restart apache
  service:
    name: apache
    state: restarted
