---
- hosts: Clients
  remote_user: root

  vars:
      service: "service"

  tasks:

  - include_role:
      name: Web
    when:
      - ansible_os_family == "RedHat"
      - service == "Web"

  - include_role:
      name: apache
    when:
      - ansible_os_family == "Debian"
      - service == "Web"
